# Generated by Django 5.2.13 on 2026-04-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgendamentoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paciente_id", models.IntegerField()),
                ("medico_nome", models.CharField(max_length=255)),
                ("inicio", models.DateTimeField()),
                ("duracao_minutos", models.IntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "agendamentos",
            },
        ),
    ]
