# pylint: disable=invalid-name
# Generated by Django 5.2.13 on 2026-04-30 18:01

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamentomodel",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
    ]
